### your site title here

title: Gabriel B. Apolinário
description: Physics | Postdoc researcher at ENS de Lyon

#baseurl: /gradfolio #name of GitHub repository
url: https://gapolinario.github.io/
  #custom url to be used instead of GitHub repository
email: #

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
email: gabriel.brito_apolinario@ens-lyon.fr
twitter: "gbapolinario"
#linkedin: "#"
github: "gapolinario"
#researchgate: "#"
orcid: "0000-0003-4230-4072"
#scholar: "7RL5_NsAAAAJ&"
arxiv: "apolinario_g_1"
rss: ""
# lattes: http://lattes.cnpq.br/9462982316488552

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  #- _projects

plugins:
#  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
